# Generated by Django 4.0.5 on 2022-11-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_vendor_companyname_vendor_gstnumber_vendor_pancard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustmer',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
